name: ichat
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  hive_generator: ^1.1.2
  provider: ^6.0.2
  socket_io_client: 2.0.0-beta.4-nullsafety.0
  cupertino_icons: ^1.0.2
  url_strategy: ^0.2.0
  http: ^0.13.4
  rive: ^0.8.1
  flutter_local_notifications: ^9.2.0
  scrollable_positioned_list: ^0.2.3
  image_picker: ^0.8.4+10
  file_picker: ^4.4.0
  permission_handler: ^9.2.0
  scroll_to_index: ^2.1.1
  flutter_svg: ^1.0.3
  flutter_app_badger: ^1.3.0
  extended_image: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.7
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: Vazir
      fonts:
        - asset: asset/fonts/vazir.ttf
    - family: OpenSans
      fonts:
        - asset: asset/fonts/opensans.ttf
  
  assets:
    - asset/images/
    - asset/rives/